{% set name = "furl" %}
{% set version = "1.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "6bb7d9ed238a0104db3a638307be7abc35ec989d883f5882e01cb000b9bdbc32" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - six >=1.8.0
    - orderedmultidict >=0.7.8

test:
  imports:
    - furl

about:
  home: https://github.com/gruns/furl
  license_file: LICENSE.md
  license: PUBLIC-DOMAIN
  summary: 'URL manipulation made simple.'
  dev_url: https://github.com/gruns/furl
  doc_url: https://github.com/gruns/furl

extra:
  recipe-maintainers:
    - pmlandwehr
