{% set name = "furl" %}
{% set version = "1.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "47b25a4c4e48d926c399a5538466134fc7aed8b357a6290dcb83e3a1b9f3aa29" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six >=1.8.0
    - orderedmultidict >=0.7.8

test:
  imports:
    - furl

about:
  home: https://github.com/gruns/furl
  license_file: LICENSE.md
  license: PUBLIC-DOMAIN
  summary: 'URL manipulation made simple.'
  dev_url: https://github.com/gruns/furl
  doc_url: https://github.com/gruns/furl

extra:
  recipe-maintainers:
    - pmlandwehr
