# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QZIO4P/8r0Owl9dSuTJbugx8DCu1sT+h+PqIqadc4i2QaNU0G7//acF3sunASnvLrglQkVtWcZnnhDrShLIkyksrnmxktY7yKbIhq2i3B0tvJMs3oeiozAfwYNY4wy6YSMpxoDt0LBuhWaiMorciKiOc1lYAZKUx7ncTXi23WiiNK6ukeujiJG2Us2A5qDwNFgjnUqJX3uvBbS9KL7qp3lB3e0hn/pp2GpwSElCCY0fHmYkjA7hDjW7JmH6lEuz9lmpz7QQiOt0SS2WigSLpVolZQ3NWKbvVzTqkqZ8IR52dDQCH/s7iCgNFo8SiCI2jDT1I5DU7qn22K01MYPA89U6VrBB1SQJt7qj4jCpV4y1RDtBnqycdaw4u3gOZcJp6pc7YQzgzVc1F0ORgYtuOpeAMMrhDpfAsVjFsfMmrUuK8hCEfx2hmFocflYjJZO2eScg3JGZzGJ3cfRPX/FGt6i+RlLIDert/qAMPRhdvCXf7tWrwOb6IOeydH+BGUUl4GCvyYb7THUzr36vA5iahft4Y/bzYOba8+ubc9GusXEWGrHQGyEkN1SuhFOnUx2cQPsffFE7ePqrOxsVqooetysty/yMEpV71h6RnjxC6mMQXptKVtRkCu/Lwv8/83wxtts50BSgtyVVogXkmqFCP+j4j/+TJuT0lNBapDR2FHd4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
