travis:
  secure:
    BINSTAR_TOKEN: AHgmP3nRYK7iu+1ZOuQM7Mvzv/NsT0cvDdFhozoREYd2TtPWoAx+OmBkbuQxHnWLsV+tjGlfkMwcZSfUb9okIQbpsdehQ/gu6aaq0oF29gfReCCxw2CpsqbkxwO77ZAz5tUUDX0xQtWn2z95V8uf0CxWaYTL88fb1GAck8glIgmMftLvmScjPj2vProD+mBt6e4gHJ6d+LbfeRJu8yvw+zxpFzZbvrnFsPdOGpWuAq95JOr9EmP1yeaCmR5gxu8kX9CszznKbM1qwf0oyZwlMtRr+n7dGVAZ3HYNF/hqgl4g3AjusD5dP550cuFAddKWdhgSp62pI0E1GsSbXognocJQDsh8tfvaTGsLZstHVV7FKEll6f2Fq0tmDO1pquTV6cqxe4a//FNSlOgEKZ+HRda3NFYf8IZDur4XoeiY46IjMvxyctL17eJhEitstrH16vAfS+47yBqLHyGI5osNcJlU4GSEtBuaGH89yZnp/eBgZAeEwIfDBO2azqj3Mfp0xMCh0DIBGmC5mEskoxU6DNDpSLeX7bfrRNtolKDKcVIA3BUIMLArF/RF4jwInopWxsqGqBHdukfzjh2vkUEz/c85w4qRAGRpCTTxVFw53ym2uB/SZKfaK+kHIAdAFUGsoM7/ZdAHvsnCTtYPOL0nlQGcdOnQGUbb5uu//gbFV0c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
