travis:
  secure:
    BINSTAR_TOKEN: Roz5zzRspwUsfIhTY+tKao5j4vZu5XtJD2lOq5eQ0JeS0s0TnUccCKd+49G4Rl6ucfnDeFmMLnWJiNRu9PFW15ESahvv0AqzUK7cKZkEFkz7B4EhX/kHkvFf5y2DhTfsVevQJTkZEbW6o2f98aw8noE65U5nKnBQB7aZ4AzUgdJhLSHgqedSOP9R6e+MFjuZ8urhw9z/b0dIvgCyUG799nmle3uuzTp57VzX8wFDwGloY99ANcsYABelcWuKp6d6EHqR6sh/14067iX3Ky22JBZky1XurBJcCM2YtNBw05ZUYKMKznSDicigEA5i1h9bKV8mjnKZUsYRZ5QzJSh9aP2TrPT/jbLuYPzMVKqKWeNBdhwISmO8gpIOPynmVK7muog0+NPyXWE3ffPyR4IlRmsrHAJch0J+TjRaHyyCULsrlIJ5sSeufrVJWiPcs3E6MNnYphMmblP84RoV72ZLbCYJU2M6T6Wykzyao+WFVEpj6v0ExCvn8bUIwg6E3eNGFB9NWNuPUF4eFYpWgMuQ0sCuWAYM4flzxPTKkN2MiUHqN0D2Ykuqm0WVomXcP9r2LcZF/j0Q+GjHlNJ56w8NqR8oJMSSvGM/xH5/8zKqRbbTYDvxPqXCpCdTRP89lCU0ZiPlp0YtJ/USlPVvezVaCIpcFdyqVQpht++d6Bp4wDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
