travis:
  secure:
    BINSTAR_TOKEN: SuvezYxTmwuRDreEyCVBaWzn3FeyyGq+dMr5UfNOzSkYYaE9VQ1Mr7qcLprqdL+oScFAOqo283iknwSk96lG3C7BFcIAz5JwJ7lLy/szNK+11Ok62GllciV2p0OCa+CSh+3Gb2Y69fMCSHNOM0837YZjQV0zQq4bxHhyVrCicJadPJ7S0gJqX3NFdQY/gzhSO8qKBdtT/tD3p4IN2YXdVdrrBS0YHRF3Yr8UqszSpk6EP1QmF3VsLQvhrYx+34tl7jXZK8BzTFVbA/1yOikZASMq3dDXvBzAik8juGrpxMaznC0UpThzc2VznBosv7D2rMU/I8Nr39rxEh/kj6jp4WVoEiKF9sEh9nhCGPuIavl35HpHRX7u7EpGsggqyV0VOxyWuwuMesEutXuz46EgXY7qYJBq2LGx/6cN8QLiV/Xn/Q4y8KP/Bocmj3GxE54YSEf51uOdjw6Gsg1u1CiI1ZuDYDdWOA7yoLNW1KApnhTrWpxDN8whAtSeABtlBwW9JUe0KQiF5DruMoDDqFoVgVJuIE3Q2VObaS9uDToOL/sxq9oWLFc88EitvSWtNwJjSeBpPUtz6ThAcnoG7qFBo8ktjaAaXRLYr56SFEiRnbx/F8HNm+Phi77nj//jafTINfbcSgsTxMfogdPC6J7lh7SjyOGqd436BlSEaMQ97ng=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
