travis:
  secure:
    BINSTAR_TOKEN: UiXS+PI/euyD9aswxD8fBhkxK6iDrXmEU+pWkiS0qNYx0ph0u7Afj3brWQFPv0w8ZmqiuzuK+QDnqhhySP5Pb18KfYmrGrZUmifWXxAHrlAtKCftgZlVy2qmbtzx/m/OabAsRAUADIDPmZ+2GX6b02L3t9sE8eC7fEmER0j9oV8m7KseBUsXJRVjYHlFHra9UHrAcJ2vHknEbDr9mvguNVP5uTRgZNyKHwo2s3w+rWbRaBUztTdbBuv1egrr6r4QqeKqBesCBGd+XrBhZN7RBeRanW6sPca/2L6M38ZzNiLyyVSyzh5Br9uLCB9Fx7pNLbJ48AMg1cmFh/JdCUu1l6Te6q7t1dYXFKMOfcQj+GqSjos54qrvVoEPmJFKzN6sjS6OlDHfZYQceSY8+PqIPdSY1C5iRdoHuUhuHiXsMkJtBLPADbozf+CG1V8vIv+ml0yFY8ktC6hofUxDy8+szRRR3B4nd49fMcGusFzpyRf5X5kR/j4G64wgW46KpLLRFqnUaYp0esRaqZexPAibqxc9GNHoHElC93HojjC4QSEo2RGImuSbjiEXCN8NPRs09FxIgbPr03WEr+JjqcIlJvsT5ieipVEz8DTSCzkS5/XE8liRyjzoaUDZ+dXvN/FDDRtKtVk5n/W6QFcVW4M90VUZ4TTVUoKzsj3D2zvUuwQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
