travis:
  secure:
    BINSTAR_TOKEN: dxwwttrPjffRFn6iippk4cZEgkKl2ED8glJlHd8db+TeTvmN6v94xp4xmrYcSIphVBHj4R8RLoMVHqBkUNlxu6tWSWzjYIHUP3slUnABnPKxrlP/3fC4NjnxN2r8BkiJoUqP0P/r8/r+bcBDtGRTaY3pqT/rrSzHXgBaamZkbTpxU+niWjyK1Oj2aOZFTg+3ZamdG8DY4IVatF4Un+sgHnsp+UMuBvzCuuBMVEjPkVrvXoYsvBii5NoZtSItfQ5bVaq3eDggZvWEhN+h6RCPC6Wbna882mQImKlLvG36sR5vVB2kEpaLhjTGohJxtEL1sULlJMsZTVgc71jPVyxeStHCeEloH9mUmI494lzd5+Gw4wHNvNYVpI/w2XQmoXo4CC5onNlpH0H2WJ4sfsr0fEvP9noxsGF1Gx8tZOnFH7u1iKie4FGFJpBbInZvsTMjPtkWH9kT1epjFwVRf8kPo7FqacuxDAycElvQu9Nk0kVTtCl0nQnGiQDEY+qgaT5SO9nFRIm3iFJxvNeIvnr1GxxkUHfryGYTQkLJX1u4jYUgrPggvrhahO+eEE6La1TVjzQxPjX6AMVhCVjOHj+yASqCQlVm1coM9V4tsx90Trp4nKPNobvBzy96AoRIEp9otPN02nAUxqru16mY4aDIRZ9lmU4dKa0vN/e6pFIUjug=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
