travis:
  secure:
    BINSTAR_TOKEN: D+3FWjkRpUwJNIjHt1Cb9fCRMcjcDQ2e4TCzRXi01HYlBEKvIIViw8YrsCqc01BGrTjZFBAdN0VkFRbB//soHwZabVb5fYKWa7ye5WNuLUY1m/FWsTEVvHcST8BPEC+k6FfqLbs3fDMB/FachDTVJMMmXPFOuonhUSiSSHOQSQZ/wjMO8mrdXfUpESiZLILI3KzrRlpFMpRh5Yb4pSi7z7ficehsWRjATMMmNbg+dnfmSXoJoRIGw6PH7XlRQQv+W9fiC+HKGvoEYG9BV4C2ASvBxuvzt02C8YDM6li4Xbp/PSTpdy5s4nFVGiVzSkb6Y/lXSeNZsy/0k4ECLU8SoZGQg+9aJ/dXXyq5LSfRhPJTTeKEtpcJVNcB+UKcDTQp4DqV1g0kUtUJE3ZYZSE9CDAl8J29ma2YyE/GOR4WF1ETTN5J4CxmybCDSDOHSd00wUkZToVxaDPnijJnuEM7DeKwAy49F2X9p9zyM63MXo64uEjhGJDbZjWWh91sk4KWecCJyGCzOSn1QT/wL5kWgLkBnWdFIW18bZGpvdhMiLq8Hl7OiP+IgvpUz3/RHyXvec3wQdH89p5K0mHag+lGHiYBm5bj8PjgGuLKJSCZ/ruTU6x6dkLne1b2mDCbopK5NhSuNNbe4/vp4wUOtXALC3OU+rBFDRStj3zppMV0Cig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
