travis:
  secure:
    BINSTAR_TOKEN: QZIO4P/8r0Owl9dSuTJbugx8DCu1sT+h+PqIqadc4i2QaNU0G7//acF3sunASnvLrglQkVtWcZnnhDrShLIkyksrnmxktY7yKbIhq2i3B0tvJMs3oeiozAfwYNY4wy6YSMpxoDt0LBuhWaiMorciKiOc1lYAZKUx7ncTXi23WiiNK6ukeujiJG2Us2A5qDwNFgjnUqJX3uvBbS9KL7qp3lB3e0hn/pp2GpwSElCCY0fHmYkjA7hDjW7JmH6lEuz9lmpz7QQiOt0SS2WigSLpVolZQ3NWKbvVzTqkqZ8IR52dDQCH/s7iCgNFo8SiCI2jDT1I5DU7qn22K01MYPA89U6VrBB1SQJt7qj4jCpV4y1RDtBnqycdaw4u3gOZcJp6pc7YQzgzVc1F0ORgYtuOpeAMMrhDpfAsVjFsfMmrUuK8hCEfx2hmFocflYjJZO2eScg3JGZzGJ3cfRPX/FGt6i+RlLIDert/qAMPRhdvCXf7tWrwOb6IOeydH+BGUUl4GCvyYb7THUzr36vA5iahft4Y/bzYOba8+ubc9GusXEWGrHQGyEkN1SuhFOnUx2cQPsffFE7ePqrOxsVqooetysty/yMEpV71h6RnjxC6mMQXptKVtRkCu/Lwv8/83wxtts50BSgtyVVogXkmqFCP+j4j/+TJuT0lNBapDR2FHd4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
