travis:
  secure:
    BINSTAR_TOKEN: mkfupkI8CHxmGWavKNBLe8s2UNoKF1JXT9t/yMl/3aTeTWYk7hd0FYly63cFhVR0m6CZ/GTcY53mKs+2OYIv0sTuSzchkhWrJQ5CN5Sla6cfteLvxKFvBAKNucRWHRAv6QZV+fX0KpqPeUeJi5JtLsHtiIzFxO+2qSJ/e/qPqBde4PGX2iijLBjQj4pgHZOtu+Lc2lVrqzS06H4c9RcqQzC75BILCpAHvEqND4k+2tLGry9R+XCJGf9D+ZlSAvh/DfObHJmw9SuLEKnD+MZ+jcYcIyHIEjVASNKfX6ojMgZNI+c9kITjjsLbvGz1GkCE6vYvv4Pcsssw+x0/cT7DFrc/iHq44KYIeZPgDfQ00DsN3dtidkAvUG/ToATuOk8+J2Y9rHp4HaaYM0Bj+fSeV86OCHwoOKNl3hQldz/v1C9yWLoCIq7kzSTP4jknUrNEtKdkrExm0qsRgKRUM6+X1C/WEGFoSYedoHTe/pTSQMw+NH7i9Qg71qCdPx2Xnnp9xI0uQALOWEWbLwdZQcxxccqSWv4UNoDnbBXPXIpfICNXptgGSIWvVrSuVgyCSRbrgtuXLduYBSbqCtAcBf7W8qAj86fi6C165RRJAkWabAWoeItXvZZxWyw/cRbGMf5q359cQYclW0/pVD5pu9WEmAh7VTRI95JGdydvhCbE2zE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
