travis:
  secure:
    BINSTAR_TOKEN: V0QOlqGFvtLemwvxanlMy8+2kwxc+y/By1v0WFdOgvBo+z33gCx/psEnxFqN36OLhPiNbEvQRh6FyomiA0f1b7D7V//ecPuAkIB0DPKt8aLERst7JP3oBZglFQc/ibeNfCToeZPOR3FIl/vK6Pw0HbnCLNoXbgOjkcO5fSNTMg0zjfhNF1zOP509jDopRTm2P2kpJALIY47WVb2LUCzEtYoJ+dJHca2x5ezMCSP4mAQRUJO4vy3aVpfhjmlqINFuej0bqWrSOoTHthrLdBJcIzpRztHfHet6Utw8k/ioSWQODbXeK4hT86AYjJBQ0i+phYzwq1VKertBCRywf1WKss+bE0vTv5H4NCGH4cceibBCicxNsYqC1y35Ih+A9okjDo0u9pV2Wym29meBHiy/4lKv3lgPzXv+yQ9XDpon423Ia17M08FoonuDxrE+BAqxAcKRkeSAM1l6Rmig1bGIMzLBmeFlBTcV/p3rpvL1DyTd2gfQ7Sw0rc/YVeqDEJPYYIMAdl/VSbIysGK5KYVlVOPzbQ6NAvFzQ/syG1oOABnSjBPZlr3Np//bV1o+U7FVW23Ni75LfcWPir7M4PhtORK5XafurdRFbkp4FcTvb7fPOBf2ntagNboCbUE3uxjgnAuLOVV9vm6Z1iaHiEHJ5tZWj21V1vrw6K1mMJT4T/U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
