travis:
  secure:
    BINSTAR_TOKEN: UnIy7mJ9VpzGaKcrSUx8LjGqNl3aZd8rHXX2ZUvImbk2mC/Mjj2OIO/aqFranos0TCw7RP0UzB3kAgXWJX8oGlX8pYLJPieJ6xr53J9pNpzz0Yf4LZJmptri56CLOYnq58xowlMV69Jttv9BGUDr3ewWQ4fiZUaAsAkSvp0Rd4u/3LqBu9ALFfDfflMwlZwWRBHd25NcMmBwT16f3ilW12b2m1hf0u7hGw8O9dtSJykIt4Rl+t1NAEBpMUmC0eOb7uetj4TeYvQPaaHcDubit6FfjCyELT7jWoEUfvVpDpjS9o7HhhoxGBH2dPkI3+slWwTsYdeJi/oMy3wTwQ0PVCOE9MPoqO4xkqKfDcZ4QUGXUUkZflUeBa3IC8H74nKFEYMK2grlkUQx81gQfWRE5f//qIXboloQpkUB4ZK1utfKl/2Bf4eyJRa0K4hXK5jhvPiAPCMuI7iMm/ltP+xnrUk8L9+yX6KHif6f663gjNF5a3beKRKRj/WqcwhayrKfT5w5c2ptfrHIw4xLayxDzb3PfibSIHlmetPaEgqIT2YvCFewYM6dOP/MV1M12MkeGXQbcbgIHcicCTKIto7puLCBwz06iGEjgl3qiSZ0+UDUEzxLOGNuu3fa83eYGQsGmssFFzU8Hu/6c8EgJnfnNFOKr3xpr/0bZ8DWbRUCC8U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
