travis:
  secure:
    BINSTAR_TOKEN: Ba3UyXtvk2Rh8Q3L3O7itwIzVjFgDcCwaMLBLpfGSU/S8i3Ev8g9qaRu8RdqnMnrpkHg2n+FKFLiq/iPqj2TeqICsZMRDT78mGO6bxvDik21jqyHBtlxxdYqMLHpK9L31hO02fthCfZBVsxJxzjZMMSYC26uMtB9opzXKdkmFuVbdu2L+wlWY1hRhcaC3wY4nkD6QntO7uvp9LUhkGCs+j+JLBT1n25rTVvn4nUKN5dH6xp4H9CGAeCu6XVnbultbOhWI7RTvHFUE8VJHlgAm4g6xJv9N9fdx+vStAaDoyJMMBwncoODqGfGv+qFmBOFZlhJQWXQeac+mIEKpOTIaWxyKJDxoFz5ee94bNb3BetS3Bgl9IBS77LwIjRIijn3hKw8w/NB61vh74daKAd0Rzh5QyTLmsLk2uY/VC1iUY34bL5GBxT390lkqUNOBg+07WfcGjl/B2nyzIR/YYH3mlGFIxLCaAaHHI8GMZKTqki/7VMhDqhqG1VjLbLRIelIhnIA2Ajhlgr/fVJgd0YI+k1E/Wq/6PzDL2fEYF6eIu1OK48Wd44qdaO0zSxSqgt8Q2fTiWbQB2LvWWL16aOAz1pBmo6VE4cxtYwEQxQWDWEtQzYWxEQBi0b27bxV9DHEZiRObTlxqoE3sV04I0xMo7G7w4j8iA+ycJGonrpRRfo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
