travis:
  secure:
    BINSTAR_TOKEN: hLIECUTSx+d2QZL4ECCdJ7Si03Fywko6kIuerSmy6DOkcHku0Cgbdu4M1wfY/k0xZEGpnmcFYlp1f9kX6AZwEOwQT5rrQUWSaz+R3FrrTICDrXuiWyLBdLCJ2/jdhIAw0UalD1DqoBBXtkLs/yXZeMMhaFHVf+nPya+dh2izavku5DWPkTDYCm/O13HfcinuTzsjXRaRSiKyf8vKOL0fe8d6Qt1ul1DQg9jKR/smdubxLXvomzj0kRS2CPJCFchqq3GpbJyd0v4qrfvF/34geghgksh/lDA0RVD4GZup9yVXzZXpHdtp5fdDmAHOUPTRto/ygjkbhk1fe/qXHFdPlsVGmrslBissaaqzD05E0+QI22/7Vu4SQDeCJUItyWBZVkX4DyQxbMXa8CsH9QxhSNwXpeGCteGvAJb08956UYwU8BL6lAQPP97uMoVAQsp7iYh5DeoQWQeJDwysO7J6pIO2PWL/T8NKBH3IzE7IY9X4JhZb67FZGngoRXUQhWOFq6f46nNYyqGyB0YjXB4Zs3bgebBpD13cEkB3pIg+Lp/OjXfygNXhw5fY163yjv3yYrMMmYuEa0L/qyMidAMVo/Bdudif+0sllzyzSK3p1fS51pVGuztvRKvTYiQfQ8gfvElu60sydQeqgrypm7CYnV4TIispbr2q9gltQ3KXJFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
